# VOLUMEの動作確認用
# docker build -t akiyoshi83/t_data .
# 間違えてrmしないようにrunしておくがstopした状態でも/dataは使える
# docker run -itd --name data akiyoshi83/t_data
FROM busybox
MAINTAINER mail@akiyoshi.info

VOLUME /data
